name: Deploy with docker
on:
  push:
    # 分支
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  workflow_dispatch:
#  schedule:
#    - cron: '10 1 * * *'
#    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkou

      - name: 获取最后一条提交日志
        id: git_log
        uses: Edisonboy/latest-git-log-action@main
        with:
          tag: origin/master

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 缓存 Maven 依赖
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 构建上传okex组件
        run: |
          mvn clean deploy package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_REPO }}
          TZ: Asia/Shanghai